#! /bin/sh
compton &
sxhkd &

~/.config/polybar/launch.sh &
nitrogen --restore &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color "${xrdb:color2}"
bspc config normal_border_color \#4c566a
bspc config focused_border_color \#d8dee9

bspc config border_radius 5

#bspc config top_padding 55
#bspc config left_padding 50
#bspc config right_padding 50
#bspc config bottom_padding 50


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
