#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x bspwmbar > /dev/null || bspwmbar &
#~/.config/polybar/launch.sh
nitrogen --restore
nm-applet &
#blueman-applet &
#udiskie -t &

bspc monitor eDP-1 -n 1 -d 1 2 3 4 5
bspc monitor DP-3 -n 0 -d  6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12
bspc config border_radius	10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Emacs state=tiled

#bspc rule -a main.py state=floating


