# Use zsh as default
set-option -g default-shell /bin/zsh

# Set true color
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm*:Tc"

# Enable mouse
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

unbind r 
bind r source "~/.config/tmux/tmux.conf"

# Set Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
#set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'omerxx/tmux-sessionx'

#set -g @catppuccin_flavour 'latte' # or frappe, macchiato, mocha

set -g @dracula-plugins "weather cpu-usage ram-usage"
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-show-fahrenheit false
set -g @dracula-fixed-location "Zoetermeer"
set -g status-position top


# Set vi-mode
set-window-option -g mode-keys vi 
# Key bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Split horizontally in CWD with \
unbind %
bind '\' split-window -h -c "#{pane_current_path}"

# Split vertically in CWD with -
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Open panes in current directory
bind '-' split-window -v -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"

# pane movement
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
